// <auto-generated />
namespace SpicePro.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addmigrationsformodelclasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmigrationsformodelclasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202102210903181_Add migrations for modelclasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
